/* HAMODYBR Tools V2.4/V2.5 — clean tool URLs + native sharing */
(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const toast=msg=>{let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)};
function appRoot(){const base=$('base')?.href;if(base)return new URL(base);const path=location.pathname,marker='/hamodybr-tools/',i=path.indexOf(marker);if(i>=0)return new URL(location.origin+path.slice(0,i+marker.length));return new URL('./',location.href)}
const toolUrl=id=>new URL(encodeURIComponent(id)+'/',appRoot()).href;
const toolName=c=>c?.querySelector('b')?.textContent.trim()||'HAMODYBR Tool';
async function copy(text){try{await navigator.clipboard.writeText(text)}catch{const a=document.createElement('textarea');a.value=text;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}}
async function shareCard(card){const id=card?.dataset.id;if(!id)return;const name=toolName(card),url=toolUrl(id),data={title:`${name} — HAMODYBR Tools`,text:`${name} — fast, free and private browser tool.`,url};try{if(navigator.share){await navigator.share(data);return}await copy(url);toast('Tool link copied.')}catch(err){if(err?.name==='AbortError')return;await copy(url);toast('Tool link copied.')}}
function enhanceCard(card){if(!card||card.dataset.hbLinkReady==='1')return;const id=card.dataset.id;if(!id)return;card.dataset.hbLinkReady='1';card.dataset.href=toolUrl(id);card.tabIndex=0;card.setAttribute('role','link');card.setAttribute('aria-label',`Open ${toolName(card)}`);if(!$('.v2-share',card)){const b=document.createElement('button');b.className='v2-share';b.type='button';b.title='Share tool';b.setAttribute('aria-label',`Share ${toolName(card)}`);b.innerHTML='<span aria-hidden="true">↗</span><em>Share</em>';card.appendChild(b)}card.addEventListener('keydown',e=>{if(e.target!==card)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();location.href=card.dataset.href}})}
function enhance(){const grid=$('#grid');if(!grid)return;$$('.card',grid).forEach(enhanceCard);if(grid.dataset.hbCleanLinks==='1')return;grid.dataset.hbCleanLinks='1';grid.addEventListener('click',e=>{const card=e.target.closest?.('.card');if(!card)return;const share=e.target.closest?.('.v2-share');if(share){e.preventDefault();e.stopImmediatePropagation();shareCard(card);return}if(e.target.closest?.('.v2-fav'))return;if(!e.isTrusted)return;e.preventDefault();e.stopImmediatePropagation();const url=card.dataset.href||toolUrl(card.dataset.id);if(e.metaKey||e.ctrlKey||e.shiftKey){window.open(url,'_blank','noopener');return}location.href=url},true)}
function loadV25(){if(document.querySelector('script[data-hb-v25]'))return;const s=document.createElement('script');s.dataset.hbV25='1';s.src=new URL('v2.5-core.js?v=250',appRoot()).href;document.head.appendChild(s)}
function boot(){enhance();loadV25();const grid=$('#grid');if(grid)new MutationObserver(enhance).observe(grid,{childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();