function readU32(a,o){return new DataView(a.buffer,a.byteOffset,a.byteLength).getUint32(o,false)}
function setU32(a,o,n){new DataView(a.buffer,a.byteOffset,a.byteLength).setUint32(o,n>>>0,false)}
function typeAt(a,o){return String.fromCharCode(a[o],a[o+1],a[o+2],a[o+3])}
function listBoxes(a,start,end){const out=[];let p=start;while(p+8<=end){let size=readU32(a,p),head=8;if(size===1){if(p+16>end)break;const dv=new DataView(a.buffer,a.byteOffset,a.byteLength),hi=dv.getUint32(p+8,false),lo=dv.getUint32(p+12,false),big=hi*4294967296+lo;if(!Number.isSafeInteger(big)||big<16)break;size=big;head=16}else if(size===0)size=end-p;if(size<head||p+size>end)break;out.push({start:p,size,type:typeAt(a,p+4),head,end:p+size});p+=size}return out}
const simpleContainers=new Set(['moov','trak','mdia','minf','stbl','dinf','edts','udta']);
function childStart(b){if(simpleContainers.has(b.type))return b.start+b.head;if(b.type==='meta')return b.start+b.head+4;if(b.type==='stsd')return b.start+b.head+8;if(b.type==='avc1'||b.type==='avc3'||b.type==='encv')return b.start+b.head+78;return null}
function findPath(a,target){function rec(start,end,path){for(const b of listBoxes(a,start,end)){const next=path.concat(b);if(b.type===target)return next;const c=childStart(b);if(c!==null&&c<b.end){const r=rec(c,b.end,next);if(r)return r}}return null}return rec(0,a.length,[])}
function bitsFromBytes(a){const out=[];for(const x of a)for(let i=7;i>=0;i--)out.push((x>>i)&1);return out}
function bytesFromBits(bits){const b=bits.slice();while(b.length%8)b.push(0);const out=new Uint8Array(b.length/8);for(let i=0;i<b.length;i++)out[i>>3]|=b[i]<<(7-(i&7));return out}
function ebspToRbsp(a){const out=[];let zeros=0;for(const b of a){if(zeros>=2&&b===3){zeros=0;continue}out.push(b);zeros=b===0?zeros+1:0}return new Uint8Array(out)}
function rbspToEbsp(a){const out=[];let zeros=0;for(const b of a){if(zeros>=2&&b<=3){out.push(3);zeros=0}out.push(b);zeros=b===0?zeros+1:0}return new Uint8Array(out)}
class BR{constructor(a){this.a=a;this.i=0}bit(){if(this.i>=this.a.length*8)throw new Error('Unexpected end of SPS');const v=(this.a[this.i>>3]>>(7-(this.i&7)))&1;this.i++;return v}bits(n){let v=0;for(let j=0;j<n;j++)v=v*2+this.bit();return v}ue(){let z=0;while(this.bit()===0){z++;if(z>31)throw new Error('Invalid Exp-Golomb')}return (2**z)-1+(z?this.bits(z):0)}se(){const c=this.ue();return c&1?(c+1)/2:-(c/2)}}
function skipScalingList(br,n){let last=8,next=8;for(let j=0;j<n;j++){if(next!==0){const d=br.se();next=(last+d+256)%256}last=next!==0?next:last}}
function locateVui(rbsp){const br=new BR(rbsp),profile=br.bits(8);br.bits(8);br.bits(8);br.ue();let chroma=1;if([100,110,122,244,44,83,86,118,128,138,139,134,135].includes(profile)){chroma=br.ue();if(chroma===3)br.bit();br.ue();br.ue();br.bit();if(br.bit()){const count=chroma!==3?8:12;for(let i=0;i<count;i++)if(br.bit())skipScalingList(br,i<6?16:64)}}br.ue();const poc=br.ue();if(poc===0)br.ue();else if(poc===1){br.bit();br.se();br.se();const n=br.ue();for(let i=0;i<n;i++)br.se()}br.ue();br.bit();br.ue();br.ue();const frameMbs=br.bit();if(!frameMbs)br.bit();br.bit();if(br.bit()){br.ue();br.ue();br.ue();br.ue()}const vuiFlagPos=br.i,vui=br.bit();if(!vui)return{vuiFlagPos,vui:false};if(br.bit()){const ar=br.bits(8);if(ar===255){br.bits(16);br.bits(16)}}if(br.bit())br.bit();const videoSignalFlagPos=br.i,videoSignal=br.bit();let fullRangePos=-1,colorDescFlagPos=-1,colorDesc=false,primPos=-1,transferPos=-1,matrixPos=-1;if(videoSignal){br.bits(3);fullRangePos=br.i;br.bit();colorDescFlagPos=br.i;colorDesc=!!br.bit();if(colorDesc){primPos=br.i;br.bits(8);transferPos=br.i;br.bits(8);matrixPos=br.i;br.bits(8)}}if(br.bit()){br.ue();br.ue()}const timingFlagPos=br.i,timing=br.bit();return{vuiFlagPos,vui:true,videoSignalFlagPos,videoSignal,fullRangePos,colorDescFlagPos,colorDesc,primPos,transferPos,matrixPos,timingFlagPos,timing,timingDataPos:br.i}}
function intBits(v,n){const a=[];for(let i=n-1;i>=0;i--)a.push(Math.floor(v/(2**i))&1);return a}
const U8_1=intBits(1,8),TIMING=[...intBits(1000,32),...intBits(240000,32),1];
function patchTiming(bits,loc){if(!loc.vui){const minimal=[0,0,1,1,0,1,0,1,...U8_1,...U8_1,...U8_1,0,1,...TIMING,0,0,0,0];bits.splice(loc.vuiFlagPos,1,1,...minimal);return}if(!loc.timing)bits.splice(loc.timingFlagPos,1,1,...TIMING);else bits.splice(loc.timingDataPos,65,...TIMING)}
function patchBt709Limited(bits,rbspAfterTiming){const loc=locateVui(rbspAfterTiming);if(!loc.vui)throw new Error('VUI missing after timing patch');if(!loc.videoSignal){const payload=[1,1,0,1,0,1,...U8_1,...U8_1,...U8_1];bits.splice(loc.videoSignalFlagPos,1,...payload);return}bits[loc.fullRangePos]=0;if(!loc.colorDesc){bits.splice(loc.colorDescFlagPos,1,1,...U8_1,...U8_1,...U8_1);return}bits.splice(loc.primPos,8,...U8_1);bits.splice(loc.transferPos,8,...U8_1);bits.splice(loc.matrixPos,8,...U8_1)}
function patchSps(nal){if(nal.length<5)throw new Error('SPS too short');const header=nal[0],rbsp=ebspToRbsp(nal.slice(1));let bits=bitsFromBytes(rbsp),loc=locateVui(rbsp);patchTiming(bits,loc);const interim=bytesFromBits(bits);patchBt709Limited(bits,interim);const rbspNew=bytesFromBits(bits),ebspNew=rbspToEbsp(rbspNew),nalNew=new Uint8Array(1+ebspNew.length);nalNew[0]=header;nalNew.set(ebspNew,1);return nalNew}
function parseAvcc(a,b){const p=b.start+b.head,end=b.end,payload=a.slice(p,end);if(payload.length<7||payload[0]!==1)throw new Error('Unsupported avcC');let q=6;const prefix=payload.slice(0,6),ns=prefix[5]&31,sps=[];for(let i=0;i<ns;i++){const l=(payload[q]<<8)|payload[q+1];q+=2;sps.push(payload.slice(q,q+l));q+=l}const np=payload[q++],pps=[];for(let i=0;i<np;i++){const l=(payload[q]<<8)|payload[q+1];q+=2;pps.push(payload.slice(q,q+l));q+=l}return{prefix,sps,pps,tail:payload.slice(q)}}
function buildAvcc(parsed){const parts=[],prefix=parsed.prefix.slice(),patchedSps=parsed.sps.map(patchSps);if(patchedSps[0]?.length>3){prefix[1]=patchedSps[0][1];prefix[2]=patchedSps[0][2]}parts.push(prefix);for(const s of patchedSps)parts.push(new Uint8Array([s.length>>8,s.length&255]),s);parts.push(new Uint8Array([parsed.pps.length]));for(const p of parsed.pps)parts.push(new Uint8Array([p.length>>8,p.length&255]),p);parts.push(parsed.tail);const payloadLen=parts.reduce((n,x)=>n+x.length,0),box=new Uint8Array(8+payloadLen);new DataView(box.buffer).setUint32(0,box.length,false);box.set([97,118,99,67],4);let o=8;for(const x of parts){box.set(x,o);o+=x.length}return box}
function patchNclx(a){let count=0;for(let i=4;i+15<a.length;i++){if(a[i]!==99||a[i+1]!==111||a[i+2]!==108||a[i+3]!==114)continue;const start=i-4,size=readU32(a,start);if(size<19||start+size>a.length)continue;if(typeAt(a,i+4)!=='nclx')continue;const dv=new DataView(a.buffer,a.byteOffset,a.byteLength);dv.setUint16(start+12,1,false);dv.setUint16(start+14,1,false);dv.setUint16(start+16,1,false);a[start+18]=0;count++}return count}
function adjustChunkOffsets(a,delta,threshold){if(!delta)return 0;let changed=0;const dv=new DataView(a.buffer,a.byteOffset,a.byteLength);function rec(start,end){for(const b of listBoxes(a,start,end)){if(b.type==='stco'){const count=dv.getUint32(b.start+b.head+4,false);let p=b.start+b.head+8;for(let i=0;i<count;i++,p+=4){const v=dv.getUint32(p,false);if(v>=threshold){const nv=v+delta;if(nv>0xffffffff)throw new Error('stco overflow after Fast Start patch');dv.setUint32(p,nv,false);changed++}}}else if(b.type==='co64'){const count=dv.getUint32(b.start+b.head+4,false);let p=b.start+b.head+8;for(let i=0;i<count;i++,p+=8){const hi=dv.getUint32(p,false),lo=dv.getUint32(p+4,false),v=hi*4294967296+lo;if(v>=threshold){const nv=v+delta;if(!Number.isSafeInteger(nv))throw new Error('co64 offset overflow');dv.setUint32(p,Math.floor(nv/4294967296),false);dv.setUint32(p+4,nv>>>0,false);changed++}}}const c=childStart(b);if(c!==null&&c<b.end)rec(c,b.end)}}rec(0,a.length);return changed}
export function patchMp4(buffer){const a=new Uint8Array(buffer),path=findPath(a,'avcC');if(!path)throw new Error('H.264 avcC configuration box not found');const top=listBoxes(a,0,a.length),moov=path.find(x=>x.type==='moov'),mdat=top.find(x=>x.type==='mdat');if(!moov||!mdat)throw new Error('Unexpected MP4 layout');const avcc=path.at(-1),newBox=buildAvcc(parseAvcc(a,avcc)),delta=newBox.length-avcc.size,work=a.slice();for(const box of path.slice(0,-1)){if(readU32(work,box.start)===1)throw new Error('64-bit ancestor box size not supported');setU32(work,box.start,box.size+delta)}const out=new Uint8Array(work.length+delta);out.set(work.slice(0,avcc.start),0);out.set(newBox,avcc.start);out.set(work.slice(avcc.end),avcc.start+newBox.length);const fastStart=moov.start<mdat.start;const chunkOffsetsAdjusted=fastStart?adjustChunkOffsets(out,delta,mdat.start):0;const nclxCount=patchNclx(out);return{buffer:out.buffer,delta,nclxCount,fastStart,chunkOffsetsAdjusted}}
